import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {Toaster} from 'react-hot-toast';
import React from "react";
import {Providers} from "@/components/providers"
import PusherProviders from "@/components/providers/pusher";
const inter = Inter({subsets: ['latin']})
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";

export const metadata: Metadata = {
    title: 'Petcung.vn- Hệ thống cửa hàng & dịch vụ cho thú cưng',
    description: 'Generated by create next app',
    icons: '/images/favicon.png'
}


export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {

    return (
        <html lang="en" suppressHydrationWarning>
        <body>
            <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
            <Providers>
                <PusherProviders>
                    {children}
                </PusherProviders>
            </Providers>
            <Toaster/>
        </body>

        </html>
    )
}
